export default {
  common: {
    login:"Login",
    level1: "Level 1",
    level2: "Level 2",
    level3: "Level 3",
    remarks: "Remarks",
    add: "Add",
    submit: "Submit",
    copy: "Copy",
    cancel: "Cancel",
    delete: "Delete",
    category: "Category",
    confirm: 'Confirm',
    save: "Save",
    other: "Other",
    edit: "Edit",
    customer: "Customer",
    accumulatedCustomers: "Accumulated customers",
    myCustomers:"My customers",
    accumulatedProfit: "Accumulated profit",
    withdrawAvailable: "Withdraw available",
    my: "My",
    myTeam: "My team",
    myOrders: "My orders",
    them: "Team",
    order: "Order",
    data: "Data",
    dataAnalysis: "Data analysis",
    analysis: "Analysis",
    vip: "VIP",
    vipRules:"VIP rules",
    rules: "Rules",
    manifesto: "Manifesto",
    weChat: "WeChat",
    nickname: "Nick name",
    remain: "Remain",
    expiry: "Expiry",
    amount: "Amount",
    commission: "Commission",
    all: "All",
    deliveryPending: "Delivery pending",
    sent: "Sent",
    distributor: "Distributor",
    level: "Level",
    levelRules: "Level rules",
    contact: "Contact",
    basicInfo: "Basic info",
    name: "Name",
    mobilePhone: "Mobile phone",
    EmailAddress: "Email address",
    inviter: "Inviter",
    paymentMethod: "Payment method",
    list: "List",
    today: "Today",
    yesterday: "Yesterday",
    pastWeek: "Past week",
    pastMonth: "Past month",
    custom: "Custom",
    team:"Team",
    background: "Background",
    invite: "Invite",
    friend: "Friend",
    salesTarget: "sales Target",
    distributionRules: "Distribution rules",
    salesData: "Sales data",
    filter: "Filter",
    startingTime: "Starting time",
    finishTime: "Finish time",
    recipientInfo: "Recipient info",
    logisticsInfo: "Logistics info",
    detail: "Detail",
    color: "Color",
    specifications: "Specifications",
    orderNumber: "Order number",
    orderTime: "Order time",
    productPrice: "Product price",
    special: "Special",
    deliveryCost: "Delivery cost",
    buyerComment: "Buyer comment",
    completed: "Completed",
    "个客户":"customers",
    "个订单":"orders",
    distributionCenter:"Distribution center",
    managementTeam:"Management team",
    distributionOrders:"Distribution order"
  },

}
