export default {

  common: {
    login:"登录",
    level1: "大类",
    level2: "中类",
    level3: "小类",
    remarks: "备注",
    add: "新增",
    submit: "提交",
    copy: "复制",
    cancel: "取消",
    delete: "删除",
    category: "品类",
    confirm: '确定',
    save: "保存",
    other: "其他",
    edit: "编辑",
    customer: "客户",
    accumulatedCustomers: "累计客户",
    myCustomers:"我的客户",
    accumulatedProfit: "累计收益",
    withdrawAvailable: "可提现金额",
    my: "我的",
    myTeam:"我的团队",
    myOrders: "我的订单",
    them: "团队",
    order: "订单",
    data: "数据",
    dataAnalysis: "数据分析",
    analysis: "分析",
    vip: "VIP",
    vipRules:"VIP活动规则",
    rules: "规则",
    manifesto: "合作宣言",
    weChat: "微信",
    nickname: "昵称",
    remain: "剩余",
    expiry: "有效期",
    amount: "成交额",
    commission: "佣金",
    all: "全部",
    deliveryPending: "待发货",
    sent: "已发货",
    distributor: "分销员",
    level: "等级",
    levelRules: "等级规则",
    contact: "联系Ta",
    basicInfo: "基本信息",
    name: "姓名",
    mobilePhone: "手机号",
    EmailAddress: "电子邮箱",
    inviter: "邀请人",
    paymentMethod: "打款方式",
    list: "列表",
    today: "今日",
    yesterday: "昨日",
    pastWeek: "近一周",
    pastMonth: "近一月",
    custom: "自定义",
    team:"团队",
    background: "团队背景",
    invite: "邀请",
    friend: "好友",
    salesTarget: "销售目标",
    distributionRules: "分销规则",
    salesData: "销售数据",
    filter: "筛选",
    startingTime: "开始时间",
    finishTime: "结束时间",
    recipientInfo: "收件信息",
    logisticsInfo: "物流信息",
    detail: "详情",
    color: "颜色",
    specifications: "规格",
    orderNumber: "订单号",
    orderTime: "下单时间",
    productPrice: "商品价格",
    special: "商品优惠",
    deliveryCost: "运费",
    buyerComment: "买家留言",
    completed: "已完成",
    "个客户":"个客户",
    "个订单":"个订单",
    distributionCenter:"分销中心",
    managementTeam:"管理团队",
    distributionOrders:"分销订单"
  },

}
